[package]
name = "metal_3_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core-graphics-types = "0.1.3"
objc = "0.2.7"
hassle-rs = "0.11.0"
metal = "0.27.0"
cocoa = "0.25.0"
winit = "0.27"